sonar.projectKey=rohatorakci_Yazilim-Yapimi-Projesi
sonar.organization=rohatorakci

# Flutter kodlarımızın olduğu klasör (Başındaki # işaretini kaldırdık ki aktif olsun)
sonar.sources=lib

# Kodlama biçimi
sonar.sourceEncoding=UTF-8
sonar.exclusions=lib/ai_assistant.dart