// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsNvgTEv0Y6T3b59dDbWSg4hVCtljx6FI',
    appId: '1:952090414657:web:7124a1bdd57439c5d780c0',
    messagingSenderId: '952090414657',
    projectId: 'yazilim-yapimi-d7144',
    authDomain: 'yazilim-yapimi-d7144.firebaseapp.com',
    storageBucket: 'yazilim-yapimi-d7144.firebasestorage.app',
    measurementId: 'G-V7BD1Z37NK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJBF61_RmtcsIIME9j-EQagYyXUvH8P4Q',
    appId: '1:952090414657:android:d8577c1888df577dd780c0',
    messagingSenderId: '952090414657',
    projectId: 'yazilim-yapimi-d7144',
    storageBucket: 'yazilim-yapimi-d7144.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtLjh2-Vioh8iSLRc5u0XVHQHFVbnV_HQ',
    appId: '1:952090414657:ios:2c5fbda7776b87abd780c0',
    messagingSenderId: '952090414657',
    projectId: 'yazilim-yapimi-d7144',
    storageBucket: 'yazilim-yapimi-d7144.firebasestorage.app',
    iosBundleId: 'com.example.yazilimYapim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtLjh2-Vioh8iSLRc5u0XVHQHFVbnV_HQ',
    appId: '1:952090414657:ios:2c5fbda7776b87abd780c0',
    messagingSenderId: '952090414657',
    projectId: 'yazilim-yapimi-d7144',
    storageBucket: 'yazilim-yapimi-d7144.firebasestorage.app',
    iosBundleId: 'com.example.yazilimYapim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsNvgTEv0Y6T3b59dDbWSg4hVCtljx6FI',
    appId: '1:952090414657:web:156e300352c88bccd780c0',
    messagingSenderId: '952090414657',
    projectId: 'yazilim-yapimi-d7144',
    authDomain: 'yazilim-yapimi-d7144.firebaseapp.com',
    storageBucket: 'yazilim-yapimi-d7144.firebasestorage.app',
    measurementId: 'G-TYCVS5E9F5',
  );

}