# Podfile
platform :ios, '14.0'

# Flutter'ın kendi iç ayarlarını çektiği yer
import_with_path = File.expand_path(File.join('..', '..', '..', '..', 'bin', 'cache', 'pkg', 'sky_engine', 'lib', 'flutter_export_environment.sh'), __FILE__)

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Flutter paketlerini (Firebase dahil) otomatik olarak buraya çeker
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # Tüm paketlerin iOS 14.0 ile derlenmesini zorunlu kılıyoruz
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end